services:
  - type: web
    name: nelna-tray-system
    env: node
    region: singapore
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: SESSION_SECRET
        generateValue: true
      - key: NODE_ENV
        value: production
