const fs = require('fs');
const lines = fs.readFileSync('db.js', 'utf8').split('\n');

let out = [];

// Block 1: 0 to first '// Compile models'
let idxCompileModels = lines.findIndex(l => l.includes('// Compile models'));
out.push(...lines.slice(0, idxCompileModels));

out.push('// Compile models');
out.push('const LocationModel = mongoose.model(\'Location\', LocationSchema);');
out.push('const CounterModel = mongoose.model(\'Counter\', CounterSchema);');
out.push('const StockTransferModel = mongoose.model(\'StockTransfer\', StockTransferSchema);');
out.push('const UserModel = mongoose.model(\'User\', UserSchema);');
out.push('const CustomerModel = mongoose.model(\'Customer\', CustomerSchema);');
out.push('const TransactionModel = mongoose.model(\'Transaction\', TransactionSchema);');
out.push('const ActivityLogModel = mongoose.model(\'ActivityLog\', ActivityLogSchema);');
out.push('');
out.push('// Helper function to map _id to id');
out.push('const mapDoc = (doc) => {');
out.push('    if (!doc) return null;');
out.push('    const obj = doc.toObject();');
out.push('    obj.id = obj._id;');
out.push('    return obj;');
out.push('};');
out.push('');
out.push('// Helper function to generate location-specific document numbers');
out.push('const generateDocNo = async (locationCode, type) => {');
out.push('    // type: \'TFR\' or \'GRN\'');
out.push('    const prefix = locationCode ? `${locationCode}${type}` : `SYS${type}`;');
out.push('    const counterId = `${locationCode || \'SYS\'}_${type}`;');
out.push('    const counter = await CounterModel.findByIdAndUpdate(');
out.push('        counterId,');
out.push('        { $inc: { seq: 1 } },');
out.push('        { new: true, upsert: true }');
out.push('    );');
out.push('    const seqNum = counter.seq.toString().padStart(5, \'0\');');
out.push('    return `${prefix}${seqNum}`; // e.g. HOTFR00001');
out.push('};');
out.push('');
out.push('// Locations CRUD');
out.push('const Location = {');
out.push('    getAll: async () => {');
out.push('        const locations = await LocationModel.find({});');
out.push('        return locations.map(mapDoc);');
out.push('    },');
out.push('    getById: async (id) => {');
out.push('        const doc = await LocationModel.findById(id);');
out.push('        return mapDoc(doc);');
out.push('    },');
out.push('    create: async (locationData) => {');
out.push('        const id = locationData.id || Date.now().toString();');
out.push('        const newLocation = new LocationModel({');
out.push('            _id: id,');
out.push('            name: locationData.name,');
out.push('            code: locationData.code,');
out.push('            address: locationData.address,');
out.push('            currentStock: parseInt(locationData.currentStock) || 0');
out.push('        });');
out.push('        await newLocation.save();');
out.push('        return mapDoc(newLocation);');
out.push('    },');
out.push('    update: async (id, locationData) => {');
out.push('        const loc = await LocationModel.findById(id);');
out.push('        if (loc) {');
out.push('            if (locationData.name) loc.name = locationData.name;');
out.push('            if (locationData.code) loc.code = locationData.code;');
out.push('            if (locationData.address) loc.address = locationData.address;');
out.push('            if (locationData.currentStock !== undefined) loc.currentStock = parseInt(locationData.currentStock) || 0;');
out.push('            await loc.save();');
out.push('            return mapDoc(loc);');
out.push('        }');
out.push('        return null;');
out.push('    },');
out.push('    delete: async (id) => {');
out.push('        if (id === \'main\') throw new Error(\'Cannot delete main branch\');');
out.push('        await LocationModel.deleteOne({ _id: id });');
out.push('    }');
out.push('};');
out.push('');
out.push('// Stock Transfer (GRN) CRUD');
out.push('const StockTransfer = {');
out.push('    getAll: async (locationId = null, role = \'user\', queryParams = {}) => {');
out.push('        let filter = { isDeleted: { $ne: true } };');
out.push('        ');
out.push('        if (role !== \'admin\' && locationId) {');
out.push('            filter.$or = [');
out.push('                { fromLocationId: locationId },');
out.push('                { toLocationId: locationId }');
out.push('            ];');
out.push('        }');
out.push('');
out.push('        if (queryParams.startDate || queryParams.endDate) {');
out.push('            let dateCondition = {};');
out.push('            if (queryParams.startDate) {');
out.push('                dateCondition.$gte = new Date(queryParams.startDate);');
out.push('            }');
out.push('            if (queryParams.endDate) {');
out.push('                const end = new Date(queryParams.endDate);');
out.push('                end.setHours(23, 59, 59, 999);');
out.push('                dateCondition.$lte = end;');
out.push('            }');
out.push('');
out.push('            if (queryParams.page === \'receive\') {');
out.push('                filter.$and = filter.$and || [];');
out.push('                filter.$and.push({');
out.push('                    $or: [');
out.push('                        { status: \'PENDING\', dispatchedDate: dateCondition },');
out.push('                        { status: { $ne: \'PENDING\' }, receivedDate: dateCondition },');
out.push('                        { status: { $ne: \'PENDING\' }, receivedDate: { $exists: false }, dispatchedDate: dateCondition }');
out.push('                    ]');
out.push('                });');
out.push('            } else {');
out.push('                filter.dispatchedDate = dateCondition;');
out.push('            }');
out.push('        }');
out.push('');
out.push('        if (queryParams.srcLocation && queryParams.srcLocation !== \'All\') {');
out.push('            filter.fromLocationId = queryParams.srcLocation;');
out.push('        }');
out.push('        if (queryParams.destLocation && queryParams.destLocation !== \'All\') {');
out.push('            filter.toLocationId = queryParams.destLocation;');
out.push('        }');
out.push('        if (queryParams.status && queryParams.status !== \'Select\' && queryParams.status !== \'All\') {');
out.push('            filter.status = queryParams.status;');
out.push('        }');
out.push('        if (queryParams.distributor && queryParams.distributor !== \'Head Office\') {');
out.push('            filter.distributor = new RegExp(queryParams.distributor, \'i\');');
out.push('        }');
out.push('        if (queryParams.serialNo) {');
out.push('            filter.serialNo = new RegExp(queryParams.serialNo, \'i\');');
out.push('        }');
out.push('        if (queryParams.refNo) {');
out.push('            filter.refNo = new RegExp(queryParams.refNo, \'i\');');
out.push('        }');
out.push('        if (queryParams.rep && queryParams.rep !== \'Select\') {');
out.push('            filter.rep = new RegExp(queryParams.rep, \'i\');');
out.push('        }');
out.push('        if (queryParams.route && queryParams.route !== \'Select\') {');
out.push('            filter.route = new RegExp(queryParams.route, \'i\');');
out.push('        }');
out.push('');
out.push('        const transfers = await StockTransferModel.find(filter).sort({ dispatchedDate: -1 });');
out.push('        return transfers.map(mapDoc);');
out.push('    },');

// Now we need to append StockTransfer.dispatch onwards.
let dispatchIndex = -1;
for (let i = lines.length - 1; i >= 0; i--) {
    if (lines[i].includes('    dispatch: async (transferData) => {')) {
        dispatchIndex = i;
    }
}

if (dispatchIndex !== -1) {
    out.push(...lines.slice(dispatchIndex));
    fs.writeFileSync('db.js', out.join('\n'));
    console.log('REPAIRED DB.JS SUCCESS');
} else {
    console.log('COULD NOT FIND dispatch!');
}
